#!/usr/bin/osascript

on run argv
	set str to (item 1 of argv)

	tell application "Google Chrome"
		repeat with x from 1 to (count windows)
			set u to get URL   of active tab of window x
			set t to get title of active tab of window x
			if (u contains str and t does not start with "Developer Tools -") then
				reload active tab of window x
			end if
		end repeat
	end tell
end run
